image: python-fastmat

stages:
    - prepare
    - build
    - test
    - benchmark
    - docu

cache:
    untracked: true
    paths:

variables:
    BENCH_OPTIONS: "maxIter=0.2,maxInit=0.5,maxMem=20000"

################################################################################
codingStyle:
    stage: prepare
    script:
        - echo Checking PEP8 compliance
        - make styleCheck

################################################################################
python2-build:
    stage: build
    script:
        - rm -f *.pyc */*.pyc */*/*.pyc
        - make compile PYTHON=python2
    artifacts:
        paths:
            - fastmat/*.so
            - fastmat/*/*.so
        expire_in: 1 day
    only:
        - master


python2-test-classes:
    stage: test
    script:
        - python2 util/bee.py test -s .class -v
    only:
        - master


python2-test-transforms:
    stage: test
    script:
        - python2 util/bee.py test -s .transform -v
    only:
        - master


python2-test-algorithms:
    stage: test
    script:
        - python2 util/bee.py test -s .algorithm -v
    only:
        - master


python2-test-bee:
    stage: test
    script:
        - python2 util/bee.py list makedump
        - python2 util/bee.py list algs
        - python2 util/bee.py list classes
        - python2 util/bee.py list index
        - python2 util/bee.py list index -e
    only:
        - master

python2-benchmark:
    stage: benchmark
    script:
        - cd doc
        - "make benchmarks PYTHON=python2 OPTIONS=$BENCH_OPTIONS"
    artifacts:
        paths:
            - doc/results/*
        expire_in: 1 week
    only:
        - master

python2-docu:
    stage: docu
    script:
        - cd doc
        - "make clean"
        - "make doc PYTHON=python2 OPTIONS=$BENCH_OPTIONS"
    artifacts:
        untracked: true
        paths:
            - doc/*.pdf
            - doc/results/*
            - doc/output/*
            - doc/plots/*
        expire_in: 1 week
    only:
        - master


################################################################################
python3-build:
    stage: build
    script:
        - rm -f *.pyc */*.pyc */*/*.pyc
        - make compile PYTHON=python3
    artifacts:
        paths:
            - fastmat/*.so
            - fastmat/*/*.so
        expire_in: 1 day

python3-test-classes:
    stage: test
    script:
        - python3 util/bee.py test -s .class -v


python3-test-transforms:
    stage: test
    script:
        - python3 util/bee.py test -s .transform -v


python3-test-algorithms:
    stage: test
    script:
        - python3 util/bee.py test -s .algorithm -v


python3-test-bee:
    stage: test
    script:
        - python3 util/bee.py list makedump
        - python3 util/bee.py list algs
        - python3 util/bee.py list classes
        - python3 util/bee.py list index
        - python3 util/bee.py list index -e
    only:
        - master


python3-benchmark:
    stage: benchmark
    script:
        - cd doc
        - "make benchmarks PYTHON=python3 OPTIONS=$BENCH_OPTIONS"
    artifacts:
        paths:
            - doc/results/*
        expire_in: 1 week
    only:
        - master

python3-docu:
    stage: docu
    script:
        - cd doc
        - "make clean"
        - "make doc PYTHON=python3 OPTIONS=$BENCH_OPTIONS"
    artifacts:
        untracked: true
        paths:
            - doc/*.pdf
            - doc/results/*
            - doc/output/*
            - doc/plots/*
        expire_in: 1 week
    only:
        - master
