branches:
  only:
    - stable
    - cisetup

environment:
  global:
    CIBW_ENVIRONMENT: "FASTMAT_GENERIC=1"
    CIBW_BEFORE_BUILD: "python -m pip install -r requirements-dev.txt"
    FASTMAT_GENERIC: "1"

  TWINE_REPOSITORY:
    secure: uxrVt8G0aReV23OXS5lWKg==

  TWINE_REPOSITORY_URL:
    secure: ZOBFk0ZQrSJU2YF/RWZObU/2O9XBbQ42I9vDVg3JPd8=

  TWINE_USERNAME:
    secure: vmEPVHBcWLBeQoU4t3pl8A==

  TWINE_PASSWORD:
    secure: s5rlS2aZ0pdnIhWQrN0B0LZO5FU6B7CIp1ON4wriejs=

  matrix:
    - PYTHON: "C:\\Python35-x64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CIBW_BUILD: 'cp35-win32 cp35-win_amd64'

    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      CONDA_PY: "36"
      CIBW_BUILD: 'cp36-win32 cp36-win_amd64'

    - PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"
      CONDA_PY: "37"
      CIBW_BUILD: 'cp37-win32 cp37-win_amd64'

    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8"
      PYTHON_ARCH: "64"
      CONDA_PY: "38"
      CIBW_BUILD: 'cp38-win32 cp38-win_amd64'

    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9"
      PYTHON_ARCH: "64"
      CONDA_PY: "39"
      CIBW_BUILD: 'cp39-win32 cp39-win_amd64'

    # For Python versions available on Appveyor, see
    # http://www.appveyor.com/docs/installed-software#python

install:
  - ECHO "Filesystem root:"
  - ECHO "Installed SDKs:"

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

  # Check that we have the expected version and architecture for Python
  - "python --version"
  - "python -c \"import struct; print(struct.calcsize('P') * 8)\""

  # Upgrade to the latest version of pip to avoid it displaying warnings
  # about it being out of date.
  - "python -m pip install --upgrade pip"

build_script:
  - python -m pip install cibuildwheel==1.9 twine || python -m pip install cibuildwheel==1.4.1 twine
  - python -m pip install -r requirements-dev.txt
  - python setup.py build_ext --inplace
  - python -m pip install .

test_script:
  - python bee.py test -v
  - cibuildwheel --output-dir wheelhouse
  - twine upload "wheelhouse\\*.whl" & exit 0

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels
